### PR TITLE
Feature/fe 179/enhance mobile web app

### PR DESCRIPTION
**Pull request by BenHakimIlyass**

### CODE REVIEW

**Review by natsukiai — COMMENTED** [review]
Files reviewed, great job! I'm testing it right away on every devices.

**Comment by BenHakimIlyass** [comment]
The camera view might be a bit smaller on large mobile screens (only if the device is in portrait orientation), but I think it's okay since we inform the user to rotate to landscape for a better experience.

**Comment by natsukiai** [comment]
I have some layout issues while testing.

First on Android Expo App:
Screenshot_20211116-101554

Second on Android web App:
Screenshot_20211116-101802

**Comment by BenHakimIlyass** [comment]
Hmmm, I know why it happens.. will fix it right away 🐛 🐛 .

**Review by natsukiai — CHANGES_REQUESTED** [review]
Fix layout issues. :-)

**Comment by natsukiai** [comment]
> Hmmm, I know why it happens.. will fix it right away 🐛 🐛 .

You're a champ!

**Comment by BenHakimIlyass** [comment]
## Mobile browser layout issue
The first issue is fixed in the latest commit, but the second one is not a bug, perhaps I made it like that on purpose:

When we're on Portrait orientation, and due to the browser address bar provided by IOS we can't get the useful width of the view port(known issue in the community), which gives us the ability to set the right width to the mask and camera as well:

image

And if we try to use the css `100vh` value or Javascript `window.innerHeight` both solutions will give us the whole height including the address bar height, which will result like following:

image

So that's why I made the mask and the camera smaller only on mobile browser and Portrait orientation.

**Review by natsukiai — APPROVED** [review]

**Pull request merged**
