### PR TITLE
Fix retake/retake all + reupload buttons at the upload center step

### PR DESCRIPTION
**Pull request by alexandre-em**
## Technical description

- [x] Feature description...

## Tested on

-
- 

## Steps to reproduce

1. Enable Upload center on `InspectionCapture`
2. Run the capture process
3. Click on `Retake a photo` and then `Retake all` (if multiple compliances)
4. Expected to go to the camera screen and be able to take photos
5. Same for the reupload photo. Expected to reupload the photo without going on the camera screen

## Screenshots (optional):

No screenshots.

*This Pull Request template has been written and generated by Monk JS repository.*

### CODE REVIEW

**Comment by alexandre-em** [comment]
For the Damage detection process, I have the "infinite load" at the end of the capture that is caused by the compliance state (and maybe upload state) being not updated

**Comment by alexandre-em** [comment]
> > For the Damage detection process, I have the "infinite load" at the end of the capture that is caused by the compliance state (and maybe upload state) being not updated
> 
> Do you still have this behavior?

yes, I didn't work on this issue since because it was not the priority for this cycle

**Comment by natsukiai** [comment]
@BenHakimIlyass @alexandre-em 
Is this PR updated or deprecated ? I think Ilyass made changes on the Compliance. To be verified.

**Comment by alexandre-em** [comment]
> @BenHakimIlyass @alexandre-em Is this PR updated or deprecated ? I think Ilyass made changes on the Compliance. To be verified.

Yes I think we can close this PR

**Pull request closed without merging**
